name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login 
      run: docker login ghcr.io -u liangyuanpeng -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: cd openvscode-server && docker build . --file Dockerfile --tag ghcr.io/liangyuanpeng/openvscode-server:go1.19 --build-arg RELEASE_TAG=openvscode-server-v1.72.2

    - name: push docker image 
      run: docker push ghcr.io/liangyuanpeng/openvscode-server:go1.19
    - name: logout
      run: docker logout ghcr.io
